package com.thinkgem.jeesite.modules.thirdApi.customer.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Itf4appService service = new Itf4appService();
 * Itf4AppDelegate portType = service.getItf4AppPort();
 * portType.getEvaluate4App(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Itf4appService", targetNamespace = "http://app.service.com/", wsdlLocation = "http://120.27.105.107/HQInterface/Itf4appPort?wsdl")
public class Itf4AppService extends Service {

	private final static URL ITF4APPSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(Itf4AppService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = Itf4AppService.class.getResource(".");
			url = new URL(baseUrl,
					"http://120.27.105.107/HQInterface/Itf4appPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://120.27.105.107/HQInterface/Itf4appPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ITF4APPSERVICE_WSDL_LOCATION = url;
	}

	public Itf4AppService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Itf4AppService() {
		super(ITF4APPSERVICE_WSDL_LOCATION, new QName(
				"http://app.service.com/", "Itf4appService"));
	}

	/**
	 * 
	 * @return returns Itf4AppDelegate
	 */
	@WebEndpoint(name = "Itf4appPort")
	public Itf4AppDelegate getItf4AppPort() {
		return super.getPort(
				new QName("http://app.service.com/", "Itf4appPort"),
				Itf4AppDelegate.class);
	}

}
