package com.thinkgem.jeesite.modules.thirdApi.customer.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Itf4appDelegate", targetNamespace = "http://app.service.com/")
public interface Itf4AppDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<com.service.app.AppTransport>
	 */
	@WebMethod(operationName = "getEvaluate4app")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getEvaluate4app", targetNamespace = "http://app.service.com/", className = "com.service.app.GetEvaluate4App")
	@ResponseWrapper(localName = "getEvaluate4appResponse", targetNamespace = "http://app.service.com/", className = "com.service.app.GetEvaluate4AppResponse")
	public List<AppTransport> getEvaluate4App(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "setMessage4app")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setMessage4app", targetNamespace = "http://app.service.com/", className = "com.service.app.SetMessage4App")
	@ResponseWrapper(localName = "setMessage4appResponse", targetNamespace = "http://app.service.com/", className = "com.service.app.SetMessage4AppResponse")
	public String setMessage4App(
            @WebParam(name = "arg0", targetNamespace = "") List<AppMessage> arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "setTransport4app")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setTransport4app", targetNamespace = "http://app.service.com/", className = "com.service.app.SetTransport4App")
	@ResponseWrapper(localName = "setTransport4appResponse", targetNamespace = "http://app.service.com/", className = "com.service.app.SetTransport4AppResponse")
	public String setTransport4App(
            @WebParam(name = "arg0", targetNamespace = "") List<AppTransport> arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<com.service.app.Outhouse>
	 */
	@WebMethod(operationName = "getOuthouse4app")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOuthouse4app", targetNamespace = "http://app.service.com/", className = "com.service.app.GetOuthouse4App")
	@ResponseWrapper(localName = "getOuthouse4appResponse", targetNamespace = "http://app.service.com/", className = "com.service.app.GetOuthouse4AppResponse")
	public List<Outhouse> getOuthouse4App(
            @WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2);

}
